id: I64F5F723
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:06:12+00:00'
last_modified: '2022-06-07T12:13:32.289202+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21805
  title: སྔོན་འགྲོའི་ཁྲིད་ཡིག་བཀའ་ལུང་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5A7E:
      image_group_id: I4252
      title: ''
      total_pages: 584
      order: 1
      base_file: 5A7E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
